### ISSUE TITLE
All Local Levels seem to have the "any/all" pronoun

### ISSUE THREAD

**Issue by capeling** [NicknameGG/level-pronouns#1]
![2023 Oct 30 18-17-551](https://github.com/NicknameGG/level-pronouns/assets/113705504/b24e5d91-bbad-4fec-ac73-8bbb32835a2a)

**Comment by xavwashere** [comment]
i don't have a very clear understanding of this mod, but from what i can tell, the pronouns are based on level id
all local levels have undefined level ids so i think it's safe to assume all local level ids = 0
maybe 0 just corresponds to any/all?

**Comment by NicknameGG** [comment]
Yes! Pronoun assignation is based on level IDs. Level IDs are passed through a function and then determine which pronoun to be assigned.
It is intended behaviour that levels with ID 0 (Local levels) have any/all pronouns.
I think it looks silly :3, makes sense for levels with no assignation yet to have Any/All pronouns since they still havent decided which pronouns they want :3
